---
- name: NEO4j Graphing database
  hosts: all
  become: yes
  roles:
    - deimosfr.neo4j
  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
      with_items:
        - chromium-browser
        - imagemagick 
        - python-pip
    - name: Install python packages
      pip:
        name: "{{ item }}"
      with_items:
        - py2neo
